# Generated by Django 4.2.13 on 2024-11-13 23:28

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SkillsAndCompetences',
            new_name='Skill',
        ),
    ]
